apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ephemeral.yaml

configurations:
  - kustomizeconfig.yaml

namespace: flux-system

configMapGenerator:
  - envs:
      - config/env
    name: ephemeral-environment-controller
labels:
  - includeSelectors: true
    pairs:
      app: ephemeral-environment-controller
replacements:
  - source:
      fieldPath: data.KUBE_SECRET
      kind: ConfigMap
      name: ephemeral-environment-controller
      version: v1
    targets:
      - fieldPaths:
          - spec.template.spec.volumes.0.secret.secretName
        select:
          group: apps
          kind: Deployment
          name: ephemeral-environment-controller
          namespace: flux-system
          version: v1
      - fieldPaths:
          - rules.0.resourceNames.0
        select:
          group: rbac.authorization.k8s.io
          kind: Role
          name: ephemeral-environment-controller
          namespace: flux-system
          version: v1
